#!/bin/bash

docker_image_rm_tags() {
	if [ -z "$(which gum)" ]; then
		echo "gum has not been installed"
		return
	fi

	local selected_image selected_tags

	selected_image=$(docker image ls --format json | jq -r '.Repository' | grep -v "<none>" | sort | uniq | gum filter --limit=1)
	if [ -z "$selected_image" ]; then
		echo "No image selected"
		return
	fi

	selected_tags=$(docker image ls --format json | jq -r "select(.Repository==\"$selected_image\") | .Tag" | gum filter --no-limit)
	if [ -z "$selected_tags" ]; then
		echo "No tag selected"
		return
	fi

	for tag in $selected_tags; do
		docker image rm "$selected_image:$tag"
	done
}

