# For Mac
# pinentry-program /opt/homebrew/bin/pinentry-touchid for Mac
# For Mac
# pinentry-program /opt/homebrew/bin/pinentry-mac
# For Linux
pinentry-program /usr/local/bin/pinentry

enable-ssh-support

default-cache-ttl 60
max-cache-ttl 120
