# pinentry-program /opt/homebrew/bin/pinentry-touchid for Mac
pinentry-program /opt/homebrew/bin/pinentry-mac # for Mac
# pinentry-program /usr/local/bin/pinentry # for Linux

enable-ssh-support

default-cache-ttl 60
max-cache-ttl 120
